In [1]:
import pandas as pd
import numpy as np
import random as rnd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
train_df = pd.read_csv('train_LZdllcl.csv')
test_df = pd.read_csv('test_2umaH9m.csv')
# print(train_df.head())
# print(train_df.info())
# CATEGORICAL VALUES: department, region, education, gender, recruitmetn_channel
# NUMERIC VALUES: no_of_trainings, age, previous_year_rating, length_of_service, KPIs_met >80%,awards_won? , avg_training_score
# ORDINAL : is_promoted
train_df.describe()
train_df.describe(include=['O'])

               department    region   education gender recruitment_channel
count               54808     54808       52399  54808               54808
unique                  9        34           3      2                   3
top     Sales & Marketing  region_2  Bachelor's      m               other
freq                16840     12343       36669  38496               30446

In [3]:
#categorical data
train_df[['region', 'is_promoted']].groupby(['region'],as_index=False).mean().sort_values(by='is_promoted', ascending=False)#0.144
train_df[['education', 'is_promoted']].groupby(['education'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #0.0985
train_df[['department', 'is_promoted']].groupby(['department'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #no
train_df[['gender', 'is_promoted']].groupby(['gender'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #0.089
train_df[['recruitment_channel', 'is_promoted']].groupby(['recruitment_channel'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #0.1208
#numerical data
train_df[['no_of_trainings', 'is_promoted']].groupby(['no_of_trainings'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #0.0881
train_df[['age', 'is_promoted']].groupby(['age'],as_index=False).mean().sort_values(by='is_promoted', ascending=False)#0.104
train_df[['previous_year_rating', 'is_promoted']].groupby(['previous_year_rating'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #0.1636
train_df[['length_of_service', 'is_promoted']].groupby(['length_of_service'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #0.25
train_df[['KPIs_met >80%', 'is_promoted']].groupby(['KPIs_met >80%'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #0.16
train_df[['awards_won?', 'is_promoted']].groupby(['awards_won?'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #0.44(1/0)
train_df[['avg_training_score', 'is_promoted']].groupby(['avg_training_score'],as_index=False).mean().sort_values(by='is_promoted', ascending=False) #1

    avg_training_score  is_promoted
60                  99     1.000000
59                  98     1.000000
58                  97     1.000000
56                  95     1.000000
57                  96     0.979167
55                  94     0.969231
54                  93     0.892857
53                  92     0.818182
52                  91     0.649573
51                  90     0.427027
50                  89     0.279070
49                  88     0.184685
35                  74     0.170901
47                  86     0.131579
48                  87     0.128244
36                  75     0.121588
32                  71     0.120267
33                  72     0.118621
31                  70     0.116588
25                  64     0.114407
34                  73     0.112811
42                  81     0.109801
26                  65     0.108514
44                  83     0.106010
43                  82     0.104354
45                  84     0.102740
28                  67     0.101648
41                  80     0.099502
46                  85     0.097948
39                  78     0.094319
..                 ...          ...
38                  77     0.093257
24                  63     0.092067
27                  66     0.091379
37                  76     0.091085
29                  68     0.082353
23                  62     0.080690
22                  61     0.077701
40                  79     0.072414
20                  59     0.070252
19                  58     0.068493
17                  56     0.064486
21                  60     0.064037
18                  57     0.057063
16                  55     0.053899
15                  54     0.049147
6                   45     0.045521
8                   47     0.045246
12                  51     0.043886
11                  50     0.041237
4                   43     0.039773
9                   48     0.039393
13                  52     0.038793
2                   41     0.038462
10                  49     0.037300
14                  53     0.033233
3                   42     0.032258
7                   46     0.031690
5                   44     0.029851
1                   40     0.000000
0                   39     0.000000

[61 rows x 2 columns]

In [4]:
############################################
#converting NaN values to numeric value
############################################
train_df["education"].fillna("others", inplace=True)
test_df["education"].fillna("others", inplace=True)
train_df["age"].fillna(0, inplace=True)
test_df["age"].fillna(0, inplace=True)
train_df["department"].fillna(9, inplace=True)
test_df["department"].fillna(9, inplace=True)

In [5]:
combine = [train_df, test_df]
for dataset in combine:
        dataset['department'] = dataset['department'].map( {'Technology': 0, 'Procurement': 1,'Analytics': 2, 'Operations': 3, 
        'Finance': 4, 'Sales & Marketing': 5, 'R&D': 6, 'HR': 7, 'Legal': 8}).astype(int)

In [6]:
for dataset in combine:
      dataset['education'] = dataset['education'].map( {"Master's & above": 0, 'Below Secondary': 1,
      "Bachelor's": 2, "others": 3} ).astype(int)

In [7]:
# for dataset in combine:
# dataset.loc[ dataset['age'] <= 16, 'age'] = 0
# dataset.loc[(dataset['age'] > 16) & (dataset['age'] <= 32), 'age'] = 1
# dataset.loc[(dataset['age'] > 32) & (dataset['age'] <= 48), 'age'] = 2
# dataset.loc[(dataset['age'] > 48) & (dataset['age'] <= 64), 'age'] = 3
# dataset.loc[ dataset['age'] > 64, 'age']

In [8]:
for dataset in combine:
       dataset["recruitment_channel"] = dataset["recruitment_channel"].map({"referred": 0,
       "sourcing": 1, "other": 2})

In [9]:
############################################
#Droppping columns which are least correlated
############################################
train_df = train_df.drop(['gender', 'region', "department", "employee_id", "education"], axis=1)
test_df = test_df.drop(['gender', 'region', "department", "education"], axis=1)

In [10]:
test_df['avg_training_score'].fillna(test_df['avg_training_score'].dropna().median(), inplace=True)
train_df['avg_training_score'].fillna(test_df['avg_training_score'].dropna().median(), inplace=True)
test_df['previous_year_rating'].fillna(test_df['previous_year_rating'].dropna().median(),
inplace=True)
train_df['previous_year_rating'].fillna(test_df['previous_year_rating'].dropna().median(),
inplace=True)

In [11]:
#Knowing the correlation between avg_training_score and is_promoted
# train_df['ts_band'] = pd.qcut(train_df['avg_training_score'], 4)
# train_df[['ts_band', 'is_promoted']].groupby(['ts_band'],
#as_index=False).mean().sort_values(by='ts_band', ascending=True)

In [12]:
combine = [train_df, test_df]
# for dataset in combine:
# dataset.loc[(dataset['avg_training_score'] > 51.0) & (dataset['avg_training_score'] <= 60.0),'avg_training_score'] = 0
# dataset.loc[(dataset['avg_training_score'] > 38.999) & (dataset['avg_training_score'] <= 51.0),'avg_training_score'] = 1
# dataset.loc[ dataset['avg_training_score'] > 60, 'avg_training_score'] = 2
# dataset['avg_training_score'] = dataset['avg_training_score'].astype(int)

In [13]:
def write_to_csv(fname, y_pred):
    output = pd.DataFrame()
    output["employee_id"] = test_df["employee_id"]
    output["is_promoted"] = y_pred
    output.to_csv(fname+'.csv', sep=',', index=False)
    X_train = train_df.drop("is_promoted", axis=1)
    Y_train = train_df["is_promoted"]
    X_test = test_df.drop("employee_id", axis=1).copy()

In [14]:
#regression algorithm
# logreg = LogisticRegression()
# logreg.fit(X_train, Y_train)
# Y_pred = logreg.predict(X_test)
# write_to_csv("out_reg", Y_pred)
# acc_log = round(logreg.score(X_train, Y_train) * 100, 2)
# print(acc_log)
# coeff_

In [15]:
# coeff_df = pd.DataFrame(train_df.columns.delete(0))
# coeff_df.columns = ['Feature']
# coeff_df["Correlation"] = pd.Series(logreg.coef_[0])

In [16]:
#SUPPORT VECTOR MACHINE
# svc = SVC()
# svc.fit(X_train, Y_train)
# Y_pred = svc.predict(X_test)
# write_to_csv("out_svm", Y_pred)
# acc_svc = round(svc.score(X_train, Y_train) * 100, 2)
# print(acc_svc)

In [17]:
#RANDOM FOREST
# random_forest = RandomForestClassifier(n_estimators=100)
# random_forest.fit(X_train, Y_train)
# Y_pred = random_forest.predict(X_test)
# write_to_csv("out_random_forest", Y_pred)
# random_forest.score(X_train, Y_train)
# acc_random_forest = round(random_forest.score(X_train, Y_train) * 100, 2)
# print(acc_random_forest)

In [18]:
#DECISION TREE
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, Y_train)
Y_pred = decision_tree.predict(X_test)
write_to_csv("out_Decision_tree", Y_pred)
acc_decision_tree = round(decision_tree.score(X_train, Y_train) * 100, 2)
print(acc_decision_tree)

NameError: name 'X_train' is not defined